services:
  db:
    image: postgres:alpine3.15
    container_name: vibetunes_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: vibe_tunes

    ports:
      - "5432:5432"
    expose:
      - "5432"
